# Generated by Django 5.2.1 on 2025-06-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['value']},
        ),
    ]
